name: Create Storybook with GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.STORYBOOK_CICD_APP_ID }}
          private-key: ${{ secrets.STORYBOOK_CICD_SECRET }}
          # 指定しなければ、現在レポジトリ用のトークンが作られる (実質GITHUB_TOKENと同じ)
          # https://github.com/actions/create-github-app-token?tab=readme-ov-file#owner
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: bash init.sh
      - run: cd storybook && npm run build-storybook
      - uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
