name: Create Storybook with GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.STORYBOOK_CICD_APP_ID_ID }}
          private-key: ${{ secrets.STORYBOOK_CICD_SECRET }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: bash init.sh
      - run: cd storybook && npm run build-storybook
      - uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
